### PR TITLE
dtw.js server-side only

### PR DESCRIPTION
**Pull request by magosilvain**
This code does not use any client-side variables. It therefore runs more smoothly than the original code.
Furthermore, I got rid of the ee.Algorithms.If functions. The time differences between all time steps are first saved under the variable 'dt_list'. Time-constrained DTW then uses a filter (dt <= beta) to pass over the time steps that fulfill the condition.
The code is still not perfect. The timestamps of the image time series are not used by the code, but simply the timestamps of the patterns (line 102). With other words, here we make the assumption that the number of timestamps of the image time series is equal to the number of time stamps of the patterns, and that the time steps are equal. However, the timestamps of the image time series are usually available from the image properties ('system:time_start'), so they could be pulled from there.
I have commented out the code for distance type 'angular'. I haven't revised this section yet and it therefore still uses client-side for loops.

### CODE REVIEW

**Comment by wouellette** [comment]
Great thanks for the contribution! 

I think we need to make sure that the patterns and images can be of any lengths respectively, so I will modify the PR when I have time to make sure that remains a possibility (unless you are working on this and would like to submit the change at some point).

I will also update the angular distance calculation with your full server-side logic when I have some time, so as to ensure that all distance options perform equally well.

**Comment by wouellette** [comment]
The implementation provided does not work with the test code in the  `examples` folder.
Have you made sure it was working with that test case? And if not, could you provide the script you tested the function with?

**Comment by magosilvain** [comment]
I have just updated the code. Angular distance calculation is now also accepted, and the timestamps of the images can now be different from the timestamps of the patterns.
Note that the inputs to the DTWDist function have changed. This is probably why it did not work with the test code in the examples folder. The following inputs have changed:
- provide directly the image stack (variable 'stack') instead of the variable 'image_arr'. The function 'prepareBands' which can be used to generate 'image_arr' is not required anymore. I have deleted the function from the code.
- provide a list of the image timestamps under 'options' (variable 'timeseries_img'). It's actually not an option, but a required input now.

I haven't compared the outputs of the calculations with distance type 'angular' with the outputs of your code. So maybe this still needs to be done. However, I did make sure that the code provides a reasonably looking output with the 'angular' option..

**Comment by wouellette** [comment]
See [https://github.com/wouellette/ee-dynamic-time-warping/pull/2](https://github.com/wouellette/ee-dynamic-time-warping/pull/2) for follow-up on this PR.

**Pull request closed without merging**
